#!/bin/bash

action="run"
port=9000

if (( $# == 1 ))
then
  port=$1
elif(( $# == 2))
then
  action=$1
  port=$2
fi

echo "Using port $action $port"

export JAVA_OPTS="${JAVA_OPTS} -DmtdlConfig.properties=conf/application.conf"

case $action in
   clean)
      sbt clean compile "run $port"
      ;;
   update)
      sbt update compile "run $port"
      ;;
   compile)
      sbt compile "run $port"
      ;;
    *)
      echo "default"
      sbt "run $port"
      ;;
esac




