#!/bin/bash

port=9000

if (( $# > 0 ))
then
  port=$1
fi

echo "Using port $port"

action=1

if (( $# == 2))
then
  action=$2
fi


export JAVA_OPTS="${JAVA_OPTS} -DmtdlConfig.properties=conf/application.conf"

case $action in
   cleanrun)
      sbt clean compile "run $port"
      ;;
   updaterun)
      sbt update compile "run $port"
      ;;
   *)
      echo "default"
      sbt "run $port"
      ;;
esac




