#!/bin/sh

if [ ! -f data/db/h2db.mv.db ]
then
   mkdir -p data/db/
   cp conf/initialdata/h2/h2db.mv.db data/db/h2db.mv.db
fi

if [ ! -f data/maven-settings.xml ]
then
   cp conf/maven-settings.xml data/maven-settings.xml
fi

bin/minder
